name: Tests
on:
    push:
      branches:
        - main
    pull_request:

jobs:
    codecov:
        name: Code coverage on codecov
        runs-on: "ubuntu-latest"
        defaults:
          run:
            shell: bash -l {0}
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Install pyleco requirements
            uses: mamba-org/setup-micromamba@v1
            with:
              environment-file: environment.yml
              cache-environment-key: pylatest-ubuntu-latest-mamba-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
              cache-downloads: false
          - name: Python version
            run: python --version
          - name: Test for Coverage
            run: pytest --cov --cov-report=xml
          - name: Upload coverage to Codecov
            uses: codecov/codecov-action@v3
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
              directory: ./coverage/reports/
              # env_vars: OS,PYTHON
              fail_ci_if_error: true
              files: ./coverage.xml,!./cache
              flags: unittests
              name: codecov-umbrella
              verbose: true    
